version: '3.8'
services:
  mysql-db:
    image: mysql:8.0.29
    container_name: grahakarya-mysql-db
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks: 
      - mysql-connection
    volumes:
      - mysql-data:/var/lib/mysql

  mysql-admin:    
    image: phpmyadmin:latest
    container_name: grahakarya-mysql-db-admin
    environment:
      PMA_HOST: mysql-db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:      
      - "8080:80"
    networks: 
      - mysql-connection

  web:
    build: ./web
    image: diliplakshya/grahakarya-web
    container_name: grhakarya-web
    ports:
      - 3000:3000
    volumes:
      - ./web:/app

  milk:
    build: ./microservices/milk
    image: diliplakshya/grahakarya-milk
    container_name: grhakarya-milk
    ports:
      - 5001:5001
    env_file:
      - ./.env     # path to your .env file
    volumes:
      - ./microservices/milk:/app
    depends_on:
      - mysql-db

volumes:
  mysql-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/database/mysql/data/db'

networks:
  mysql-connection: