version: '3.8'
services:
  web:
    build: ./web
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
  api:
    build: ./api
    ports:
      - 5000:5000
    environment:
      - URL=http://sharma.com
    volumes:
      - ./api:/app
  db:
    image: amazon/dynamodb-local:1.20.0
    ports:
      - 8000:8000
    volumes:
      - grha:/data/db
  admin:
    build:
      context: db
      dockerfile: Dockerfile
    ports:
    - 8001:8001
    environment:
      - DYNAMO_ENDPOINT=http://db:8000
      - AWS_REGION=example
      - AWS_ACCESS_KEY_ID=example
      - AWS_SECRET_ACCESS_KEY=example
    depends_on:
      - db
volumes:
  grha: