version: '3.8'
services:
  db:
    image: amazon/dynamodb-local:1.20.0
    ports:
      - 8000:8000
    volumes:
      - grha:/data/db
  admin:
    build:
      context: db
      dockerfile: Dockerfile
    ports:
    - 8001:8001
    environment:
      - DYNAMO_ENDPOINT=http://db:8000
    depends_on:
      - db
  web:
    build: ./web
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
  api:
    build: ./api
    ports:
      - 5000:5000
    env_file:
      - ./api/.env     # path to your .env file
    volumes:
      - ./api:/app
    depends_on:
      - db
volumes:
  grha: