version: '3.8'
services:
  web:
    build: ./web
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
  api:
    build: ./api
    ports:
      - 5000:5000
    environment:
      - URL=http://sharma.com
    volumes:
      - ./api:/app