version: '3.8'
services:
  db:
    image: amazon/dynamodb-local:1.20.0
    container_name: grahakarya-dynamo-db
    ports:
      - 8000:8000
    volumes:
      - grhakarya:/data/db
  admin:
    build:
      context: db
      dockerfile: Dockerfile
    image: diliplakshya/grahakarya-dynamo-db-admin
    container_name: grahakarya-dynamo-db-admin
    ports:
    - 8001:8001
    environment:
      - DYNAMO_ENDPOINT=http://db:8000
    depends_on:
      - db
  web:
    build: ./web
    image: diliplakshya/grahakarya-web
    container_name: grhakarya-web
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
  milk:
    build: ./microservices/milk
    image: diliplakshya/grahakarya-milk
    container_name: grhakarya-milk
    ports:
      - 5001:5001
    env_file:
      - ./microservices/milk/.env     # path to your .env file
    volumes:
      - ./microservices/milk:/app
    depends_on:
      - db
volumes:
  grhakarya: