version: '3.8'
services:
  mysql-db:
    image: mysql:8.0.29
    container_name: grahakarya-mysql-db
    ports:
      - "3308:3306"
    command: --init-file /data/application/dbinit.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks: 
      - mysql-connection
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-init:/data/application

  mysql-admin:    
    image: phpmyadmin:latest
    container_name: grahakarya-mysql-db-admin
    environment:
      PMA_HOST: mysql-db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:      
      - "8080:80"
    networks: 
      - mysql-connection

  web:
    build: ./web
    image: diliplakshya/grahakarya-web
    container_name: grhakarya-web
    ports:
      - 3000:3000
    volumes:
      - ./web:/app

  auth:
    build: ./microservices/auth
    image: diliplakshya/grahakarya-auth-dev
    container_name: grhakarya-auth-dev
    environment:
      BUILD_ENV: ${BUILD_ENV}
      API_VERSION: ${API_VERSION}
      API_TITLE: ${API_TITLE}
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      SPHINX_DIRECTORY: ${SPHINX_DIRECTORY}
      LOG_CONFIG: ${LOG_CONFIG}
      LOG_FILE_PATH: ${LOG_FILE_PATH}
      LOG_FILE_NAME: ${LOG_FILE_NAME}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 5001:5001
    volumes:
      - ./microservices/auth:/app
    networks: 
      - mysql-connection
    depends_on:
      - mysql-db

volumes:
  mysql-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/database/mysql/data/db'

  mysql-init:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/database/mysql/data/sql'

networks:
  mysql-connection:
