version: '3.8'
services:
  grahakarya-auth-mysql-db-dev:
    image: mysql:8.0.29
    container_name: grahakarya-auth-mysql-db-dev
    ports:
      - "3308:3306"
    command: --init-file /data/application/dbinit.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 3s
        retries: 10
    networks: 
      - grahakarya-auth-mysql-connection-dev
    volumes:
      - grahakarya-auth-mysql-data-dev:/var/lib/mysql
      - grahakarya-auth-mysql-init-dev:/data/application

  grahakarya-auth-mysql-db-admin-dev:    
    image: phpmyadmin:latest
    container_name: grahakarya-auth-mysql-db-admin-dev
    environment:
      PMA_HOST: grahakarya-auth-mysql-db-dev
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:      
      - "8080:80"
    networks: 
      - grahakarya-auth-mysql-connection-dev
    depends_on:
      grahakarya-auth-mysql-db-dev:
        condition: service_healthy

  web:
    build: ./web
    image: diliplakshya/grahakarya-web
    container_name: grhakarya-web
    ports:
      - 3000:3000
    volumes:
      - ./web:/app

  grahakarya-auth-dev:
    build: ./microservices/auth
    image: diliplakshya/grahakarya-auth-dev
    container_name: grhakarya-auth-dev
    environment:
      BUILD_ENV: ${BUILD_ENV}
      API_VERSION: ${API_VERSION}
      API_TITLE: ${API_TITLE}
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      SPHINX_DIRECTORY: ${SPHINX_DIRECTORY}
      LOG_CONFIG: ${LOG_CONFIG}
      LOG_FILE_PATH: ${LOG_FILE_PATH}
      LOG_FILE_NAME: ${LOG_FILE_NAME}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 5001:5001
    volumes:
      - ./microservices/auth:/app
    networks: 
      - grahakarya-auth-mysql-connection-dev
    depends_on:
      grahakarya-auth-mysql-db-dev:
        condition: service_healthy

volumes:
  grahakarya-auth-mysql-data-dev:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/database/mysql/data/db/dev'

  grahakarya-auth-mysql-init-dev:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/database/mysql/data/sql/dev'

networks:
  grahakarya-auth-mysql-connection-dev:
