apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
data:
{{ printf "environments/%s/configmap.yaml" .Values.global.env | .Files.Get | indent 2 }}