apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ printf "%s-%s" .Values.global.namespace .Values.global.env }}
data:
{{ printf "environments/%s/configmap.yaml" .Values.global.env | .Files.Get | indent 2 }}