apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.PersistentVolume.VolumeClaim.name }}
  namespace: {{ printf "%s-%s" .Values.namespace .Values.env }}
spec:
  accessModes: 
    - {{ .Values.PersistentVolume.VolumeClaim.accessModes }}
  resources:
    requests:
      storage: {{ .Values.PersistentVolume.VolumeClaim.storage }}
