apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
{{ printf "environments/%s/secret.yaml" .Values.global.env | .Files.Get | indent 2 }}