FROM python:3.11.1-slim-buster
# Make /app as a working directory in the container
WORKDIR /app

# set environment variables
# Prevents Python from writing pyc files to disc (equivalent to python -B option)
ENV PYTHONDONTWRITEBYTECODE 1

# Prevents Python from buffering stdout and stderr (equivalent to python -u option)
ENV PYTHONUNBUFFERED 1

# Expose the port 5000 in which our application runs
EXPOSE 5000 

# Copy everything from ./src directory to /app in the container
COPY src /app/src
COPY tests /app/tests
COPY __init__.py .
COPY Dockerfile.test .
COPY pyproject.toml .

RUN pip3 install poetry
# already in a virtual environment by using a docker image, there's no need to build another environment
RUN poetry config virtualenvs.create false

# Installs all the required packages minus the development packages
RUN poetry install --no-dev

# Execute testcase
CMD ["python3", "-m", "pytest"]
