apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: grahakarya-dynamo-db-main
          image: amazon/dynamodb-local:1.20.0
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
        - name: grahakarya-dynamo-db-admin
          image: diliplakshya/grahakarya-dynamo-db-admin
          ports:
            - containerPort: 8001
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /data/db
              name: db-volume
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: host-pvc