apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mysql-helm.fullname" . }}
  labels:
    {{- include "mysql-helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mysql-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mysql-helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mysql-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.deployment.containers.main.name }}
          image: {{ .Values.deployment.containers.main.image }}
          imagePullPolicy: {{ .Values.deployment.containers.main.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.ports.main.containerPort }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-ConfigMap
                  key: mysql_root_password
          volumeMounts:
            - name: {{ .Values.deployment.containers.volumes.data.name }}
              mountPath: {{ .Values.deployment.containers.volumes.data.mountPath }}
              subPath: {{ .Values.deployment.containers.volumes.data.subPath }}
            - name: {{ .Values.deployment.containers.volumes.init.name }}
              mountPath: {{ .Values.deployment.containers.volumes.init.mountPath }}
        - name: {{ .Values.deployment.containers.main.name }}
          image: {{ .Values.deployment.containers.admin.image }}
          imagePullPolicy: {{ .Values.deployment.containers.admin.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.ports.admin.containerPort }}
          env:
            - name: PMA_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-ConfigMap
                  key: dns
            - name: PMA_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-ConfigMap
                  key: mysql_user
            - name: PMA_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-ConfigMap
                  key: mysql_root_password
      volumes:
        - name: {{ .Values.deployment.containers.volumes.data.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.deployment.containers.volumes.data.claimName }}
        - name: {{ .Values.deployment.containers.volumes.init.name }}
          configMap:
            name: {{ .Release.Name }}-ConfigMap