kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.PersistentVolume.Volume.name }}
  labels:
    {{- include "mysql-helm.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.PersistentVolume.Volume.storage }}
  accessModes: 
    - {{ .Values.PersistentVolume.Volume.accessModes }}
  hostPath:
    path: {{ .Values.PersistentVolume.Volume.hostPath.path }}
