apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: grahakarya-mysql-db-main
          image: mysql:8.0.29
          ports:
            - containerPort: 3306
          imagePullPolicy: Always
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-data-store-env
                  key: mysql_database
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-data-store-env
                  key: mysql_root_password
        - name: grahakarya-mysql-db-admin
          image: phpmyadmin:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-volume
          env:
            - name: PMA_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-data-store-env
                  key: dns
            - name: PMA_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-data-store-env
                  key: mysql_user
            - name: PMA_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-data-store-env
                  key: mysql_root_password
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: host-pvc