apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ printf "%s-%s" .Values.global.namespace .Values.global.env }}
type: Opaque
stringData:
{{ printf "environments/%s/secret.yaml" .Values.global.env | .Files.Get | indent 2 }}