apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ printf "%s-%s" .Values.global.namespace .Values.global.env }}
  labels: {{- include "mysql.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.ports.dev.name }}
      port: {{ .Values.ports.dev.port }}
      targetPort: {{ .Values.ports.dev.targetPort }}
      NodePort: {{ .Values.ports.dev.NodePort }}
  type: {{ .Values.service.type }}
